services:
  - type: web
    name: matematikwebsitesi
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: matematik-db
          property: connectionString

databases:
  - name: matematik-db
    plan: free

